development:
  adapter: postgresql
  encoding: unicode
  database: shortener_development
  pool: 5
  username: belkiii
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: shortener_test
  pool: 5
  username: belkiii
  password:
